### ISSUE TITLE
About Map Save Size

### ISSUE THREAD

**Issue by QMonteCarlo** [HDaoud/ORBSLAMM#2]
Hi, @HDaoud , thanks for your excellent work! I noticed your code has implemented map saving and loading. I'm not familiar with the lib for map serialization, would you be kind enough to tell the approximate size of your saved map file for a specific scene or dataset?

**Comment by HDaoud** [comment]
Hi @QMonteCarlo it totally depends on the number of key frames and map points. Currently only the saving is fully implemented. The output is an xml file that contains map’s key frames and map points. Refer to this file which is the saved map of a run on fr2_large_with_loop: it’s 45 MB:
https://drive.google.com/open?id=0Bxnz_Y_iV3T1QmZRNU45a3l3T3M
