### ISSUE TITLE
BebopDroneDecodeStream

### ISSUE THREAD

**Issue by ghost** [HDaoud/ORBSLAMM#4]
I can't find BebopDroneDecodeStream file after installed SDK3. So I try to copy this file to packages/Samples/ and compile it,but some errors occur" FlandFaceDetection.h not found".Please help me,THX

**Comment by HDaoud** [comment]
I used FLand face detection for a project where the bebop drone detect and track faces and keep them in the center of the image. You can comment the #include of that header file.
